import React from 'react';
import Carousel from '../carousel';

import Image from 'next/image';

export default function Maastricht() {
 
    const imgArray = [
        {url: '/static/img/paroisses/maastricht/image-1.jpg', legende: 'Archevêque Georges Evdokias (Wagner) avec deux de ses successeurs ultérieurs en 1980 : les prêtres David De Bruyne (Namen), Serge Konovaloff (Leuven), Guido De Vylder (Maastricht), doyen Marc Nicaise (Bruxelles) et protodiacre Pol Hommes'},
        {url: '/static/img/paroisses/maastricht/image-2.jpg', legende: 'Dédicace de l\'autel en septembre 1985. Le père Guido, le proto-diacre Pol et l\'archevêque Georges van Evdokias'},
   ];
    return (
        <div className="px-10 bio-block">
            <h2>De parochie van de hl joh. chrysostomos en servatius Maastricht</h2>
            <p>En l'année de notre Seigneur 1976, la petite communauté dédiée à St. Jean Chrysostome et St. Servatius à Maastricht, sous l'obéissance de l'archidiocèse des paroisses orthodoxes russes en Europe occidentale (souvent abrégé «rue Daru») du Patriarcat œcuménique de Constantinople. La même année, le père Guido - plus tard Mgr Gabriel - est ordonné diacre et prêtre pour cette nouvelle paroisse de la cathédrale de Paris. C'est pourquoi nous pouvons considérer cette année comme notre date de fondation. Monseigneur Gabriel est décédé en 2013.</p>
            <p>Les années soixante-dix étaient marqué dans tout notre pays par un grand élan missionnaire: construire une Église locale de langue vernaculaire. Grâce au travail du feu archimandrite Adrien du monastère à La Haye, les livres liturgiques les plus importants étaient traduits – peut-être pas parfait, mais pour une jeune paroisse il-y-avait la possibilité de célébrer le cercle liturgique.</p>
            <p>En 1976 père Guido  (De Vylder) - le futur archevêque Gabriel – était ordonné diacre et prêtre par mgr Georges de Syracuse (Tarasoff) à Paris. </p>
            <p>Au début notre communauté a profité de l’hospitalité des sœurs Ursulines, qui on mis à notre disposition une salle dans leur couvent pour les célébrations liturgiques. Cette salle était très grande et pas accessible de la rue, alors très vite nous avons cherchés une propriété à nous même. On ne peut pas dire que notre ville, si ancienne et si chrétienne - sept saints évêques dans les premiers sept siècles – a une manque de chapelles ou d’églises : mais toutes étaient trop chers, trop grands ou pas disponibles pour le culte. Alors la seule possibilité c’était d’acheter un magasin ou une ancienne maison, assez grande pour y installer un lieu de culte, avec la possibilité d’y habiter.</p>
            <p>Avec l’aide de Dieu, nous avons trouvés en 1981 un magasin de billard : mais la maison, construite fin du 19ème siècle, était en état d'abandon. Et tout d'abord, une nouvelle façade était nécessaire. En 1985, le moment était enfin venu et la nouvelle église pouvait être inaugurée, même si tout n'était pas tel que nous l'avions imaginé à l'intérieur. Mais nous aurions encore du temps pour cela.</p>
            <p>La consécration de l’église était le début d’une période plein d’élan et d’activité. La paroisse était dans ce temps complètement néerlandophone, hors deux paroissiens Grecs – eux aussi néerlandophones. Mais aussi Maastricht se développait : depuis les années nonante  les premiers immigrants de l’Est arrivaient – les plusieurs que pour un temps limité, avant d’être ‘ré-localisé’ : Russes, Ukrainiens, Roumaines, Bulgares, Serbes, mais la langue dans les services  – le néerlandais – était pour eux un empêchement.</p>
            <p>Le début du XXIème siècle était catastrophique pour l’Orthodoxie aux Pays-Bas : tout-un-coup le nombre de prêtres diminuait de 6 à 1 : Vladyka Gabriel fut nommé à Liège, le p. Lambert partait pour Nantes, le p. Martin décédé, le p. Pachom – étant diabète, ses deux jambes  étaient amputées – vivait dans une maison de repos, et le p. Séraphim, surchargé, quittait la prêtrise. Seule le p. Théodore nous restait. Pour quelques mois un prêtre américain (un ‘padre’), servant à un base de l’OTAN, est venu célébrer chez nous.</p>
            <p>Mais pas seulement la situation ecclésiastique changeait ; aussi la démographie à Maastricht subissait de changements majeurs. L’université montrait une croissance sans précédent, à cause de l’afflux d’étudiants de l’étranger : surtout d’origine de l’Europe Est et Sud. En suite du Traité de Maastricht (1992), l’université avait le droit d’attribuer des diplômes européens (pas seulement ‘nationale’). Une deuxième université (japonaise) a été créée ; de nombreux établissements d'enseignement supérieur en ville ont obtenu le statut d'université. Et surtout : la langue d’enseignement changeait en Anglais. Maintenant 15% des habitants de Maastricht sont étudiant, dont plus ou moins la moitié sont des étrangers.</p>
            <p>Après son élection comme archevêque en 2003, Vladyka Gabriel est parti pour Paris et la paroisse a dû fermer temporairement. Réouvert en 2005, c’étaient les ‘nouveaux’ qui sont venus : étudiants d’Ukraine, de Russie, de Grèce, de Chypres, d’Écosse, d’Albanie … un certain moments il-y-avaient 16 nationalités dans la paroisse. Il-y-a aussi la possibilité de faire un ‘post-doctorat’ de 3 mois, alors très souvent c’tst un ‘va-et -viens’ de fidèles dans la paroisse. </p>
            <p>Mais: pas de prêtres néerlandophones, ni de chantres néerlandophones.  Et, peu à peu la langue dans les services changeait en slavon, avec un peu d’Anglais, en gardant avec obstination un peu de néerlandais. Vladyka Gabriel envoyait deux fois pas mois un prêtre de Paris : en général des étudiants de St. Serge. Sous mgr Job cette dernière possibilité était supprimée, sans nous offrir une autre solution. Alors j’étais obligé d’aller à Pologne, en demandant le Métropolite Sawa de nous envoyer un étudiant, en lui offrant la possibilité de faire ses études à Louvain (partiellement aussi anglophone) et - en retour – célébrant deux weekends par mois dans notre paroisse. C’était que pour une temps limité.</p>
            <p>Enfin – en 2017– le bon Dieu a répondu à nos prières et le métropolite Jean a ordonné un nouveau prêtre pour notre paroisse: le prêtre Sergey Kriger. Alors maintenant à nouveau, les services peuvent avoir lieu régulièrement, encore en trois langues !</p>

            <Carousel imgList={imgArray} legende="" id="crypte" />
        </div>
    );
}
