import React from 'react';
import Carousel from '../carousel';

import Image from 'next/image';

export default function Olivierdeserres() {
 
    return (
        <div className="px-10 bio-block">
            <h2>L'église de la Présentation de la Très Sainte Mère de Dieu au Temple</h2>

            <p>La création en 1928 à Paris de l’église de la Présentation de la Très Sainte Mère de Dieu au Temple était directement liée aux activités de l’Action chrétienne des étudiants russes (ACER). « L’église du Mouvement » avait été créée au sein de la jeunesse dans l’idée d’amener cette jeunesse à l’église. Dans son livre « Le chemin de ma vie » le métropolite Euloge (Gueorguievsky) évoquait la création de cette paroisse dans les locaux de l’ACER boulevard du Montparnasse et la nomination en tant que recteur de cette église d’un prêtre remarquable, le père Serge Tchetverikov. Après de grands travaux accomplis par les futurs paroissiens pour transformer cette ancienne remise en église, celle-ci fut consacrée en l’honneur de la fête de la Présentation de la Très Sainte Mère de Dieu au Temple, soulignant ainsi l’idée d’« écclésialisation de la vie » mise en œuvre au sein du Mouvement. Dès les premières années avait été instaurée une tradition d’offices célébrés fréquemment, quotidiennement au début. </p>
            <p>Lorsque en 1936 l’hôtel particulier du boulevard du Montparnasse fut vendu, l’ACER et la paroisse  déménagèrent dans le 15è arrondissement de Paris, au 91 rue Olivier de Serres. De très nombreux émigrés russes vivaient alors dans le 15è et travaillaient dans les usines Renault. L’archiprêtre Serge Tchetverikov (1867-1947) fut le recteur de l’église de la Présentation de 1928 à 1936 et considérait que les dix années de service qu’il y avait assumées avaient été les meilleures années de son sacerdoce, liées à son activité pastorale en tant que directeur spirituel de l’ACER. A l’époque du père Serge, la paroisse se distinguait par une intense vie de prières : célébration quotidienne de la liturgie, office hebdomadaire en français, création d’une Fraternité qui regroupait dans l’amour, dans la prière et dans le service au prochain les membres du Mouvement les plus zélés. </p>
            <p>En 1937, le père Serge partit pour le monastère de Valaam en Finlande. Le père Victor Yourieff (1893-1966) fut nommé recteur en juillet 1937 et resta à ce poste jusqu’en 1966. Ancien militaire ayant participé à deux guerres, ayant été évacué avec l’Armée Blanche à Gallipoli, il devint guerrier de la foi en nourrissant spirituellement les émigrés russes pendant la seconde guerre mondiale.  Son épouse I. K. Yourieff avait pris la direction de l’école du jeudi, école qui avait accueilli 50, 80 et certaines années jusqu’à 95 élèves. Elle avait rédigé elle-même les manuels d’histoire, de littérature, de langue russe pour cette école.</p>
            <p>Le fonctionnement du Mouvement avait été interrompu durant la période de la guerre 1939-1945 et toutes les activités de ses membres s’étaient concentrées sur l’église. En 1941 l’église de la Présentation devint un centre d’aide, destiné aux prisonniers de guerre russes et aux Russes déportés par les Allemands pour des travaux forcés sur les îles Anglo-Normandes, sous la direction du hiéromoine Sylvestre (Haruns, devenu par la suite archevêque dirigeant le diocèse du Canada de l’église orthodoxe américaine). Le père Victor avait organisé avec le « Bureau d’aide » dirigé par S. M. Zernov des aides sociales pour les familles avec enfants et les orphelins. A la fin de la guerre l’église de la Présentation était devenue l’église de nombreux russes vivant dans le 15è arrondissement. En 1946, l’ACER et la paroisse ont pu, notamment en vendant des « petites briques » symboliques racheter la maison où l’église se trouve encore aujourd’hui.</p>
            <p>En 1942, Vassili Vassilievitch Zenkovsky( 1881-1962) qui était président de l’ACER, professeur à l’Institut de théologie St Serge, marguillier de l’église de la Présentation, avait été ordonné prêtre par le métropolite Euloge et nommé au poste de vicaire du recteur de l’église de la Présentation. Ils avaient officié avec le père Victor en totale unité d’âmes durant vingt ans. Remarquable prêcheur il  était également un directeur spirituel exceptionnel. S’étant mis d’accord avec les enseignants de l’Institut de théologie il avait organisé en 1949 les cours féminins de théologie dans une salle de l’église de la Présentation. Une centaine d’auditrices avait terminé ce cycle d’études, les cours ayant été dispensés durant vingt années. Le protopresbytre Basile Zenkovsky a laissé un  riche héritage en tant que scientifique et en tant que théologien. </p>
            <p>Le père Igor Vernik (1911-1994) a officié à l’église de la Présentation durant trente huit années. Durant toutes ces années il a été non seulement le directeur spirituel mais l’ami proche de nombreux paroissiens. Il avait fait un cycle d’études complet à l’Académie de théologie St Serge à Paris, il avait enseigné au Lycée russe, il avait enseigné le catéchisme au centre d’accueil pour les enfants russes de Montgeron, il avait travaillé pour le Mouvement. Il avait été également président de la commission diocésaine de contrôle des comptes et doyen des paroisses de la région parisienne. Dans les années 1980 le père Igor avait demandé au père Nicolas Rehbinder de prendre en charge la partie de la paroisse qui était passée au français. C’est ainsi que se forma une filiale, la nouvelle paroisse francophone de St Jean le Théologien. L’église de la Présentation a eu à différentes époques pour recteurs et prêtres officiants les pères Serge Tchetverikov, Lev Liperovsky, Basile Zenkovsky, Victor Yourieff, Alexis Kniazeff, Georges Sérikoff, Pierre Tchesnakoff, Igor Vernik, Grégoire Svetchine, Nicolas Rehbinder, Alexis Struve, Vlasislav Trembovelsky, Daniel Cabagnols. Le recteur actuel de l’église est l’archiprêtre Iakov Rehbinder, l’archiprêtre Mikhaïl Cusnir concélèbre avec lui dans un esprit d’unité et de respect des traditions de l’église de la Présentation.</p>
            <p>Les actions de bienfaisance ont toujours tenu une place particulière dans la vie de la paroisse. Dans les années 1930-1960, années les plus matériellement difficiles de l’émigration, la majeure partie de l’argent des quêtes était distribuée aux nécessiteux. Une association féminine d’entraide avait été fondée en 1949 à l’initiative de V. A. Zander. Des tours de garde étaient organisés pour assurer la distribution de vêtements, de chaussures  et d’aide financière aux émigrés de  la première et de la seconde vague, des quêtes permettaient d’offrir des cadeaux à l’occasion de Pâques aux  nécessiteux et aux pensionnaires des maisons de retraite, des concerts de bienfaisance étaient organisés.</p>
            <p>Le premier chef de chœur de l’église de la Présentation avait été Th. G. Spassky, qui avait imposé un style de chant inspiré par le répertoire de l’Institut de théologie st Serge. En 1968 O. N. Lavroff avait pris la direction du chœur, qu’il continue à diriger aujourd’hui avec N. N. Lebedeff. L’année du Millénaire du baptême de la Russie O. N. Lavroff avait créé un grand chœur, qui donne des concerts dans les églises catholiques et protestantes.</p>
            <p>L’iconographie de l’église de la Présentation de la Très Sainte Mère de Dieu au Temple. La première église boulevard du Montparnasse avait été installée en un temps record – 3 jours. Les frères Kovalevsky avaient fabriqué une iconostase, accroché les icônes de la Très Sainte Mère de Dieu, des saints Serge de Radonège et Séraphin de Sarov provenant de l’iconostase de campagne servant lors des congrès de l’ACER. Les icônes du Sauveur et de la Mère de Dieu peintes par sœur Jeanne (Reitlinger) avaient également trouvé leur place. Nombre d’icônes furent offertes, d’autres commandées à G. V. Morozov, paroissien et peintre d’icônes.  L’église a été décorée par de nombreux iconographes de l’émigration parmi lesquels : T. V. Eltchaninoff, G. V. Morozov, sœur Jeanne (Reitlinger), E. S. Lvoff, I. A. Kuleff, S. Tchekounoff, G. Lapierre, M. Struve, E. Ozoline, N. Spassky, E. Lefoulon-Eltchaninoff, N. Tchernetsky, N. Pampouloff, O. Platonova, O. Oustinov. La peinture murale de sœur Jeanne (Reitlinger) « Ô Pleine de grâces, en toi se réjouit toute la création ! » en l’honneur de la Très Sainte Mère de Dieu occupe une place particulière derrière l’autel. </p>
            <p>La participation active des enfants et des adolescents aux liturgies avait toujours fait partie des traditions de la paroisse. Une école paroissiale et un jardin d’enfants ont fonctionné de nombreuses années auprès de l’église de la Présentation dans le but de conserver chez les enfants l’amour de la culture russe, des traditions, de l’histoire. En 1998 il fut décidé de fermer l’école russe, tout en gardant l’enseignement du catéchisme le dimanche. Les enfants apprennent l’Ancien et le Nouveau Testament, l’année liturgique, la vie des saints, le slavon, le chant choral. Chaque année un arbre de Noël  réunit les paroissiens de tous âges autour de l’Enfant Christ.    Il y a toujours eu de nombreux cercles et communautés auprès de la paroisse. Il y avait des lectures publiques sur des sujets théologiques, littéraires, artistiques, sur la pédagogie. Aujourd’hui l’activité des cercles a fortement baissé, mais elle n’a pas totalement disparu : les cours de catéchèse pour adultes ont repris, avec lecture des Écritures saintes, O. Platonova a ouvert un cours d’iconographie.</p>
            <p>La paroisse a de tous temps été riche de paroissiens actifs et dévoués. En 1928 M. V. Lavroff-Zernov avait été la première marguillière de l’église de la Présentation, rapidement remplacée par V. V. Zenkovsky. A. A. Terentieff, E. A. Sélivanoff, A.V. Malama, S. V. Eltchaninoff, N. V.  Fried, qui est la marguillière actuelle, ont pris leur suite. Tous nos marguilliers accomplissaient leur mission avec humilité et un grand dévouement et avaient en commun un étonnant talent de pacificateur.</p>
            <p>Parmi les personnalités éminentes qui avaient fréquenté l’église de la Présentation nous pouvons citer la théologienne M. I. Lot-Borodine, l’écrivain B. K. Zaïtsev, I. A. Krivochéïne, le poète V. A. Smolensky, le peintre I. A. Kuleff, l’éditeur N. A. Struve,  C. A. Eltchaninoff, enseignant et militant religieux, N. K. Rausch,  professeur honoraire à l’université René-Descartes, N. E. Gorbanevskaya poétesse et figure de la dissidence soviétique.</p>

            </div>
    );
}
