import React from 'react';
import Carousel from '../carousel';

import Image from 'next/image';

export default function SainteFoy() {
 
    const imgArray = [
       {url: '/static/img/paroisses/saintefoy/serie1/0-essai.jpg', legende: ''},
       {url: '/static/img/paroisses/saintefoy/serie1/2-skite-sud.jpg', legende: ''},
/*        {url: '/static/img/paroisses/saintefoy/serie1/3-skite-toit.jpg', legende: ''},
        {url: '/static/img/paroisses/saintefoy/serie1/4-portail.jpg', legende: ''},
        {url: '/static/img/paroisses/saintefoy/serie1/5-cellules-moines.jpg', legende: ''},
        {url: '/static/img/paroisses/saintefoy/serie1/6-chambre-pelerin.jpg', legende: ''},
        {url: '/static/img/paroisses/saintefoy/serie1/7-bibliotheque.jpg', legende: ''},
        {url: '/static/img/paroisses/saintefoy/serie1/8-art-sacre.jpg', legende: ''},
        {url: '/static/img/paroisses/saintefoy/serie1/9-higoumene-gerasime.jpg', legende: ''},
 */  ];
    return (
        <div className="px-10 bio-block">
            <h2>Le Skite Sainte Foy </h2>
            <h3>Historique</h3>
            <p>Le Skite Sainte Foy, fondé en 1996, se situe dans les Cévennes à Saint-Julien-des-Points, un petit village de 104 habitants aux portes de la Vallée Longue. Il se présente comme un mas fortifié en pierres de schiste avec des ouvertures sur une cour intérieure. Construit sur un rocher, il surplombe la vallée et offre une magnifique vue de tous côtés. Le skite se situe au milieu d’une propriété de 3 hectares.</p>
            <p>Sainte Foy fut martyrisée au IIIème siècle à l'âge de 12 ans, décapitée car elle ne voulait pas adorer les idoles romaines. Sainte Foy est la patronne des enfants et des causes désespérées. Les ruines du château de Sainte Foy dominent la Vallée Longue, elles se situent en face de nos fenêtres. Le skite est construit sur un piton rocheux, au lieu-dit le Verdier. Au Verdier il y a des vestiges gallo-romains et celtes, c’était déjà un lieu de culte avant le christianisme. Au XIIème siècle il y avait une tour à signaux qui a une vue de 360°, allant du Col de Jalcreste, la ligne de partage des eaux, jusqu’au château de Portes qui se situe sur la Régordane, un chemin qui rejoint le chemin de Saint-Jacques-de-Compostelle au Puy-en-Velay. Au XVIème siècle, le Verdier devint un prieuré bénédictin dépendant de l’abbaye saint Victor à Marseille, il servait de poste à péage sur une piste muletière avec une garnison de 15 hommes, ce qui explique l’immense four à pain. A la Révolution française en 1789 le prieuré fut vendu comme Bien national et devint une ferme fortifiée. Nous avons, en 1996, acheté le Verdier, personne n’y vivait régulièrement depuis plus de 10 ans.</p>
            <h3>Les restaurations</h3>
            <p>Nous avons dû effectuer de nombreux travaux de restaurations et adapter les bâtiments à une communauté monastique. Nous avons été bien accueillis par les gens du village car un des moines est cévenol, ils nous ont vu travailler et demeurer en hiver. Nous avons fait restaurer les toits en lauzes de schiste par des artisans du pays, nous avons adapté les bâtiments aux normes européennes de sécurité et d'hygiène. La chapelle, dans l'ancienne magnanerie, a été décorée de fresques par Iaroslav Dobrynine, de vitraux par Henry Guérin, d'une mosaïque par Michel Patrizio, de broderies d'Emmanuelle Vernoux. Depuis 2000 nous faisons partie de VMF (Vieilles Maisons Françaises). Nous avons créé un potager bio sur les conseils de Pierre Rabhi et un verger avec des espèces anciennes, adaptées à la région. Nous avons une source qui coule toute l'année et nous sommes à 360m d'altitude ce qui explique que nous ayons des oliviers, des amandiers… Nous avons restauré avec l'aide de pèlerins des murs à pierres sèches. Nous avons participé à la réalisation d'une Voie Verte qui longe le domaine. Nous avons reçu des prix pour la qualité des restaurations. Le skite participe aux: Journées Européennes du Patrimoine, Temps des Jardins,  Journées des Métiers d’Art,  Journées de Patrimoines de Pays…</p>
            <h3>La vie quotidienne au Skite Sainte Foy</h3>
            <p>Ayant vécu au Mont Athos, au monastère Stavronikita et dans le désert de Judée à la laure Saint Sabba, nous essayons de suivre la règle des moines comme dans un monastère bien que nous ne soyons que peu de moines. Chaque jour nous devons nous adapter à des évènements imprévus en particulier les visiteurs. Nous célébrons la divine Liturgie (mélodies slaves) le mardi ou le jeudi à 9h, le dimanche et les jours de fête à 10h, avec des Vigiles la veille à 20h30. Pour une journée normale nous nous levons à 4h pour réciter notre canon de prière en cellule. Chaque moine a un canon de prière, donné par son père spirituel, à réciter chaque jour : grandes et petites métanies, lectures saintes… Puis en été à 6h (en hiver à 7h) nous célébrons l’office des Matines et des Laudes dans la chapelle avec la lecture de l’Apôtre et de l’Evangile du jour. Nous prenons ensuite le petit déjeuner en commun, un frère lit un court extrait de la règle des moines. En été nous travaillons à l’extérieur de 9h à 11h, après il fait trop chaud, en hiver nous travaillons à l’extérieur de 10h à 12h, avant il fait trop froid! Nous partageons le repas, nous mangeons les légumes du potager. Nous pratiquons un jeûne léger le lundi, mercredi et vendredi sauf en carême où chaque jour est un jour de jeûne. Nous célébrons l’office des Nones après la vaisselle. En hiver nous accomplissons un travail de 14h à 17h avec les Vêpres à 17h30. En été nous avons un moment de solitude après les Nones pour reprendre le service vers 15h puis célébrer les Vêpres à 19h. Après les Vêpres nous arrosons le potager, les arbres fruitiers, les fleurs… ensuite nous prenons séparément quelques nourritures, chacun en fonction de ses besoins et vers 20h30 nous célébrons les Complies dans la crypte. Puis nous rentrons dans le grand silence de la nuit.</p>
            <p>Nous avons trois fêtes au monastère : Sainte Foy le 6 octobre, Saint Martin le 11 novembre et Saint Sabba, à qui l’église est dédiée, le 5 décembre. Nous avons de nombreuses reliques.</p>
            <p>Nous sommes actuellement deux moines, un prêtre au sanctuaire et un frère au chœur, ce qui demande beaucoup de préparations et de vigilance. Nous devons tout faire: préparer l’église, les repas, nettoyer les cuivres, les vitres, les sols… s’occuper du jardin, couper l’herbe d’une propriété de 3 hectares, entretenir les arbres, confesser, accueillir les hôtes, accorder des entretiens… Pour la lecture pendant le repas par exemple si un moine lit, l’autre mange… dans la durée ce n’est pas supportable. Nous avons choisi qu’un moine lise un texte spirituel durant quelques minutes puis que nous partagions le repas ensemble. Quand il y a plusieurs hôtes nous prolongeons la lecture et quand les pèlerins font la vaisselle, le lecteur mange en silence. Chaque situation est adaptée aux évènements et aux imprévus.</p>
            <p>Nous avons toujours demandé la bénédiction de l’archevêque pour chaque décision importante. Le Doyen vient de temps en temps pour vérifier avec bienveillance notre rythme de vie car nous risquons, sans le vouloir, de prendre de mauvaises habitudes.</p>
            <p>Deux sœurs vivaient à la Maison du Levain à 6 kilomètres du skite. Elles avaient leur propre rythme pour les offices, les repas et le travail. Elles habitaient dans cette maison de village qui peut accueillir une vingtaine de personnes. Maintenant une des sœurs est dans un Ehpad à 10km, l'autre vit dans un monastère du Mont des Oliviers à Jérusalem. Nous organisons des stages de chant liturgique pour des paroisses francophones, des stages d’iconographie, de théologie, des retraites sur le jeûne, la prière… En été des prêtres avec leur épouse et leurs enfants ou des familles orthodoxes peuvent venir à la Maison du Levain pour une retraite. </p>
            <p>Au skite nous n’avons que trois chambres à offrir aux pèlerins et deux cellules pour accueillir des moines. Nous sommes fermés en hiver car les bâtiments sont trop difficiles à chauffer. </p>
            <h3>Les moyens de subsistance</h3>
            <p>Nous ne vivons pas de l’accueil bien que ce soit un revenu non négligeable, nous ne voulons pas de sélection par l’argent. Nous vivons de notre travail: vente de livres, de collage d’icônes, de confitures, de photos, de calligraphies. Nous proposons quelques stages. Une grande partie de la nourriture provient du domaine. Les fidèles en échange de fruits et de légumes nous donnent de l’huile, du café, du sucre, c’est du troc. Chaque mois nous vivons un miracle.</p>
            <p>Le Fr Jean a écrit plusieurs livres: Pèlerinage au Mont-Athos - Hommes de Lumière - Pierre vivante Jardin de la foi - Fondation du skite - Signes de lumière - Recettes du monastère - Art Sacré…</p>
            <h3>Qui peut venir au monastère ?</h3>
            <p>Nous accueillons pour une retraite des pèlerins orthodoxes. Pour la sainte communion nous obéissons aux règles canoniques. Nous accueillons aussi des membres de la Fraternité Saint Martin, une association qui regroupe des artistes: peintres, écrivains, musiciens, danseurs, poètes… des personnes qui témoignent de leur foi par leurs œuvres. L'association édite une revue Art Sacré. Les pèlerins viennent faire une retraite pour  partager la vie monastique et l’enseignement des Pères de l’Eglise. Ils ont parfois une question, mais ils viennent souvent pour faire silence, jeûner, pour se ressourcer, pour écrire un livre, pour prier… </p>
            <p>Il est possible d’assister chaque jour aux offices monastiques ou à la divine Liturgie. Il faut toujours téléphoner avant de venir. La visite du monastère se fait sur rendez-vous : 04 66 45 42 93 du mardi au vendredi de 14h à 17h. Il est demandé d’avoir une tenue décente.</p>


            <Carousel imgList={imgArray} legende="" id="crypte" />
        </div>
    );
}
