import React from 'react';
import Carousel from '../carousel';

import Image from 'next/image';

export default function Troyes() {
 
    const imgArray = [
        {url: '/static/img/paroisses/troyes/Chapelle-St-Jean-Baptiste.jpg', legende: ''},
        {url: '/static/img/paroisses/troyes/Troyes-Pâques-1.jpg', legende: ''},
        {url: '/static/img/paroisses/troyes/Troyes-Pâques-2.jpg', legende: ''},
        {url: '/static/img/paroisses/troyes/Troyes-Pâques-3.jpg', legende: ''},
   ];
    return (
        <div className="px-10 bio-block">
            <h2>L’Eglise orthodoxe de TROYES</h2>
            <p>L’Eglise orthodoxe de Troyes est apparue au début du XXe siècle, avec l’arrivée de l’émigration russe, fuyant les contrecoups de la Révolution de 1917. Les Russes blancs, majoritairement orthodoxes, venus chercher à Troyes du travail dans l’industrie textile, ont d’abord assisté à des offices célébrés dans des endroits de fortune par des prêtres venant de Paris et de Sens.</p>
            <p>M. ROUBATCHEV, ingénieur et directeur technique de la Teinturerie Clément Marot, où travaillaient de nombreux émigrés russes dans les années 1930, a mis à leur disposition un terrain de jardins ouvriers, situé à côté de la teinturerie, rue de Chateaudun (donnant dans la rue aux Moines).Une chapelle en bois y fut construite, qui, en fait, avait presque les dimensions d’une petite cathédrale. Tous les enfants des Russes blancs nés à cette époque y ont été baptisés. Malheureusement, elle fut détruite lors du bombardement en août 1940 du quartier du 1er Mai.</p>
            <p>Après la Seconde Guerre mondiale, la communauté orthodoxe s’est développée à la suite d’une nouvelle vague migratoire. Mais elle n’avait plus de chapelle. A partir de là, elle a dû utiliser différents lieux d’accueil. Les offices ont été d’abord célébrés dans la salle de catéchisme du Temple protestant. Puis, ce fut l’Evêché qui prêta une salle de la Maison des Œuvres, située Boulevard Victor Hugo. </p>
            <p>Dans les années 70, Wladimir YAGELLO (qui n’était pas encore prêtre) se chargea de la Paroisse. Les offices furent alors célébrés à Notre-Dame en l’Isle (Séminaire de Troyes). La petite chapelle était située au premier étage, au-dessus du réfectoire des prêtres catholiques. Les liturgies s’y déroulèrent jusqu’au 13 juin 1999, avec le Père Marcel FORESTIER, qui venait de Dijon, puis avec le Père Wladimir YAGELLO, ordonné prêtre le 2 janvier 1994.</p>
            <p>La Paroisse dut alors à nouveau changer de site. Monseigneur l’Evêque DAUCOURT prêta sa chapelle personnelle à l’Evêché, pendant deux mois jusqu’au 24 octobre 1999 ; puis, jusqu’au 17 février 2000, les liturgies eurent lieu à la Maison paroissiale de St Martin. Enfin, à dater du 26 mars 2000, Monseigneur l’Evêque Marc STENGER nous a attribué la Chapelle catholique St Jean-Baptiste, rue des Cumines, où nous sommes actuellement. C’est le Père André KREMENTZOFF qui y officie depuis le 12 octobre 2003. La liturgie dominicale est célébrée une fois par mois, précédée de Vêpres, le samedi après-midi.</p>
            <p>Différentes nationalités sont représentées parmi les fidèles : russe – d’autant plus qu’une troisième vague migratoire est apparue dans les années 90 - estonienne, serbe, grecque, ukrainienne, biélorusse…La langue commune est le français utilisé majoritairement lors des offices. La communauté se développe et participe aux activités œcuméniques. Des liens amicaux se sont tissés depuis de nombreuses années avec les Catholiques et les Protestants.</p>
            <p>Les offices ordinaires rassemblent régulièrement trente à quarante fidèles mais, en fait, on peut considérer que davantage de personnes sont concernées : ce nombre peut être beaucoup plus important selon les périodes, les circonstances, les fêtes, les cérémonies particulières comme le baptême. Certaines agapes ont pu rassembler jusqu’à soixante convives. Sur les dix dernières années, on peut estimer que plus d’une centaine de personnes sont venues à la Paroisse, de manière plus ou moins occasionnelle (certains paroissiens, par exemple, habitent loin de Troyes).</p>
            <p>On peut penser aussi que le fait de ne pas avoir un site propre à la communauté orthodoxe, aux dimensions plus importantes aussi, a pu apparaître comme un frein à un plus grand essor encore, si l’on considère par exemple la présence importante dans l’agglomération d’une forte communauté serbo-croate et arménienne par exemple.</p>
            <p>Cette situation « inconfortable » devrait avoir trouvé sa solution : en 2016, Monseigneur STENGER a proposé de nous céder, par un bail emphytéotique à titre gracieux, une grange champenoise sise à St André les Vergers. La communauté a accepté l’offre, bien que consciente des difficultés de transformation et de leur coût. Ce bâtiment, classé Monument historique, est désormais en cours de rénovation. La toiture a été refaite et un bulbe orthodoxe y a été installé. L’année 2021 devrait voir la fin de l’aménagement intérieur. Un rêve est en train de se réaliser, surtout pour les plus anciens d’entre nous, qui ont vécu le « nomadisme » évoqué précédemment.</p>
            <p>Ce rêve ne se sera pas réalisé fortuitement : il est en quelque sorte la concrétisation de l’engagement sans faille, de la grande valeur morale de la communauté, qui a accepté de relever le défi, qui n’a pas ménagé sa peine dans les diverses activités mises en place afin de recueillir des fonds pour financer les travaux. La participation aux kermesses diocésaines catholiques (permanences, réalisation de produits destinés à la vente….), la longue préparation des repas œcuméniques, les travaux de déblaiement de la grange ont concerné tout le monde. Est-ce étonnant quand on voit l’esprit de famille, la solidarité qui nous unissent à chaque rencontre, à chaque liturgie, aux agapes, le bonheur ressenti chaque fois après les tâches accomplies ? C’est aussi une façon de témoigner au Père André notre affection et de le remercier pour l’abnégation et le dynamisme qui le caractérisent, qui nous portent et nous donnent la force d’entreprendre.</p>
            <p>Nous sommes une grande famille sans aucun doute représentée par toutes les tranches d’âge. Cela nous donne une grande confiance en l’avenir, comme le fait de voir apparaître régulièrement de nouveaux visages aux liturgies. Espérons que cette nouvelle église contribuera au rayonnement toujours plus grand de notre communauté orthodoxe.</p>

            <Carousel imgList={imgArray} legende="" id="troyes" />
        </div>
    );
}
