import Head from 'next/head';
import {useRouter} from 'next/router';
import Image from 'next/image';
import Header from '../components/header/header';
import styles from '../styles/pages/home.module.css';
import {useState} from 'react';
import { getMenu } from '../model/menu';

export default function Cimetiere({menu}) {
    const router = useRouter();
    const {locale, locales, defaultLocale} = router;


    return (
        <div className={`bg-pyellow`}>
            <Head>
                <title>Le cimetière russe</title>
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Header */}
            {menu && <Header menu={menu.data}/>}

            {/* Page cimetiere */}
            <div>
                <header className={styles.header + ' relative'}>
                    <Image
                        src="/static/img/histoire/bandeau_histoire.jpg"
                        // width={1400}
                        // height={360}
                        objectFit="cover"
                        layout="fill"
                    />
                </header>
            </div>
            <main className="max-w-screen-xl pt-5 mx-auto bg-white shadow md:flex md:flex-wrap">
                <div className="mx-24">
                    <h3>Naissance de l’archevêché.</h3>
                    <img className="float-left w-1/3 mr-2" src="/static/img/histoire/tikhon.jpg" /> 
                    <p>Le 8 avril 1921 (26 mars selon l'ancien calendrier Julien) le patriarche de Moscou Tikhon (glorifié en 1989 comme Saint Tikhon) émet deux décrets (No. 423 et No. 424) confiant à l'archevêque Euloge, se trouvant en situation de réfugié à l’étranger, autorité sur toutes les églises russes en Europe occidentale. Cette décision confirme celle prise en octobre 1920 par la Haute Direction Ecclésiastique Provisoire du Sud-Est de la Russie, une structure assurant l’autorité ecclésiastique en zone non-occupée par l’Armée Rouge et coupée à ce moment-là du patriarcat de Moscou sous occupation bolchevique.  Rapidement, l’archevêque Euloge reçoit également une lettre du métropolite Benjamin de Pétrograd, lui confirmant qu’il lui transmet sa juridiction sur ces paroisses en Europe occidentale qui jusqu’à présent dépendait du métropolite de Saint-Pétersbourg (devenu ensuite Pétrograd).</p>
                    <p>C’est ainsi qu'on peut marquer la date de naissance d'un grand archevêché (même si ce nom d’archevêché ne devait s’imposer que plus tard sous la présidence de l’archevêque Georges Tarassoff) qui non seulement rassemblera des dizaines de milliers de réfugiés de l'Empire russe et leurs descendants, mais aura une résonance dans l'histoire culturelle et religieuse au-delà des limites de la diaspora orthodoxe issue des bouleversements politiques en Europe de l’Est du 20ème siècle. Cet archevêché jouera au cours de ce 20ème siècle et au siècle suivant, non seulement un rôle d’arche pour les milliers de fidèles jetés sur les routes d’un des plus grands exodes de l'histoire, mais il jouera également un rôle de témoin et un rôle de pont entre les cultures, attirant des centaines voire des milliers d'hommes et de femmes issus des populations d'Europe de l'Ouest souhaitant devenir orthodoxes ou simplement dialoguer avec l'orthodoxie ou encore, simplement curieux de connaître une foi et une culture étrangères encore mal connues. L'archevêché contribuera non seulement à une histoire inédite et prestigieuse d’une Russie d’Outre-Mer, mais aussi, à l’enrichissement des patrimoines historiques et culturels de France, du Benelux, d’Allemagne, du Royaume Uni, d’Italie, de Scandinavie et d’autres pays encore. Un travail pastoral dans des conditions difficiles, parfois extrêmes, l’entretien de monuments historiques situés sur leur territoires, le travail de recherche et d’enseignement, le dialogue avec les églises chrétiennes du monde catholique et protestant, la réalisation de nouveaux ouvrages culturels signés par des créateurs et des penseurs dont la réputation était déjà ou deviendra mondiale – architectes, peintres, compositeurs, ensembles lyriques, écrivains, historiens, philosophes, enseignants et théologiens travaillant pour l’archevêché, ses paroisses ses institutions – n’est qu’une partie de cette contribution à cette histoire dont nous célébrons le centenaire.</p>

                    <h3>Un contexte historique exceptionnel</h3>
                    <div class="float-none sm:float-left mt-2 pt-6 mb-4 pr-4 md:w-96">                     
                    	<div class="h-52 text-center mb-2"> 		
                            <iframe className="relative h-full w-full" src="https://www.youtube.com/embed/ezBDLAYc0u8" 
                            title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
                        </div>
                    </div>

                    <p>Entre 1917 et 1922, environ trois millions de réfugiés fuirent le nouveau régime soviétique (les départs massifs eurent lieu surtout entre 1919 et 1920). </p>
                    <p>Une partie de ces expatriés se retrouvèrent en dehors de l’URSS en raison de la modification des frontières (indépendance de plusieurs pays soumis à l’Empire russe avant 1918), du repli stratégique de troupes antibolchéviques (armées dites « blanches ») au-delà de ces mêmes frontières ou parce qu’ils se trouvaient déjà en poste ou en exil à l’étranger. Ces migrants — Russes, Ukrainiens, Biélorusses, Sibériens autochtones, Caucasiens ou appartenant à tout autre groupe ethnique de l’immense Empire — représentaient toutes les catégories sociales et les oppositions politiques (avérées ou perçues comme telles) ciblées par la politique de terreur extrême menée par l’Armée rouge et la Tcheka (ancêtre du KGB) : élites des grandes villes ou des provinces, nobles ou bourgeois, mais aussi, de nombreux cosaques, paysans riches ou pauvres opposés aux réquisitions de l’Armée rouge, simples soldats volontaires dans les armées blanches, petits fonctionnaires. Les institutions de toutes les religions étaient particulièrement ciblées par une campagne armée : les exécutions massives et les déportations en camp de concentration du clergé, des moines et moniales et de laïcs actifs dans l’église commencèrent dès les premiers mois qui suivirent la Révolution d’Octobre et allaient se poursuivre jusque dans les années 1930. Celà mettait en danger de mort tout le clergé ainsi que des milliers d’employés des églises — bedeaux, marguilliers, gardiens et autres vendeurs de cierges ou chanteurs. </p>
                    <p>C’est dans ce contexte que plusieurs dizaines de prêtres et trente-quatre des évêques </p>
                    <p>ayant survécu à la campagne d’arrestations et d’exécutions massives se retrouvèrent à l’étranger à la fin de la sanglante guerre civile, parmi lesquels se trouvait un des hauts ecclésiastiques les plus en vue de l’ancien Empire russe, également ancien député de la Douma, l’archevêque Euloge, en mission auprès de l’Eglise orthodoxe en Serbie en 1920 et soudain coupé du Sud de l’Empire russe  entièrement envahi par l’Armée Rouge à la fin de l’année. Ces ecclésiastiques auraient à pourvoir aux besoins spirituels de tous les autres réfugiés. </p>
                    <p>Le déplacement massif de populations, qualifié de « première émigration », un des exodes les plus importants de l’histoire contemporaine, sera le premier des trois issus de ce qui fur l’Empire russe et qui allait devenir l’URSS.</p>
                    <p>La « deuxième émigration » est une conséquence de la Seconde Guerre mondiale. Environ un demi-million de citoyens soviétiques devinrent, selon le terme administratif des Nations unies, des « DP » (Displaced Persons), des expatriés fuyant l’URSS et les nouveaux régimes staliniens en Europe centrale et orientale, des réfugiés accidentels ballotés sur les routes d’Europe par les bombardements et le flux et le reflux du front, des anciens collaborateurs de l’Axe, ou encore, des prisonniers de guerre détenus dans des camps, libérés par les alliés de l’Ouest et ne pouvant rentrer en URSS devant la menace de sanctions extrêmes (ceux qui se rendaient à l’ennemi étaient considérés comme traîtres). À ceux-là, il faut ajouter ceux de la « première émigration » habitant l’Europe de l’Est et la  Chine fuyant l’avancée des troupes soviétiques ou maoïstes (La plupart furent acceuillis en Australie ou en Californie. Quelques uns se retouvèrent néanmoins en Europe de l’Ouest).</p>
                    <p>La « troisième émigration » ou « troisième vague » arriva progressivement </p>
                    <p>à partir de 1974, après que Brejnev, sous la pression internationale, surtout américaine, eut accepté de laisser sortir tous les ans, au compte-gouttes, quelques milliers de demandeurs de visa de sortie, essentiellement à destination d’Israël. Selon les accords internationaux, un centre d’orientation en Autriche envoyait les exilés ne souhaitant pas devenir des Israéliens vers des centres d’accueil à Rome et dans sa banlieue où ils devaient attendre d’être acceptés dans un autre pays de leur choix. L’Archevêché s’impliqua pour assurer leurs besoins spirituels et même matériels. Jusqu’à la disparition de l’URSS, nombre de ces exilés de la « Troisième émigration » se retrouvèrent à Paris et en Europe Occidentale où ils augmentèrent considérablement les actifs des paroisses et des institutions de l’Archevêché. </p>

                    <h3>S’organiser en Eglise sur les chemins de l’exode.</h3>
                    <img className="float-right w-1/2 mt-2 ml-2" src="/static/img/histoire/evacuation-de-crimee.jpg" /> 
                    <p>En 1918, en pleine guerre civile, l’Église orthodoxe de l’ancien Empire russe réunie en concile viennent d’élire leur nouveau primat, le patriarche Tikhon. Rapidement coupé du reste du monde et de nombreux autres évêques russes, Tikhon est de moins en moins libre de ses mouvements et de ses paroles. En novembre 1918, 13 évêques se trouvant derrière les lignes des troupes blanches et coupés de l’administration du patriarcat à Tomsk (Sibérie) fondèrent une « Haute administration ecclésiastique provisoire ». C’est sur ce modèle qu’en mai  1919, est formée, à Stavropol au Caucase, en territoire contrôlé par les armées blanches, une « Haute Administration ecclésiastique provisoire du sud-est de la Russie ». </p>
                    <p>Le 2 octobre (15 octobre) 1920, par la Haute Administration Provisoire de l'Église du Sud-Est de la Russie (sous la direction du métropolite Antonij (Hrapovitskij) à Simferopol), l'archevêque Euloge est "chargé de l'administration de tous les russes d'Europe occidentale. églises comme évêque diocésain "</p>
                    <p>En novembre 1920, une immense flotte évacuant près de 200 000 réfugiés d’Ukraine et de la région du Don est accueillie dans le port de Constantinople avec l’aide des alliés occupant la Turquie. Le 19 novembre, tous les évêques évacués organisent à bord d’un des navires une assemblée de la Haute Administration ecclésiastique provisoire du sud-est de la Russie qu’ils renomment en décembre « Haute Administration ecclésiastique russe à l’étranger ». Cette organisation sera approuvée par le patriarche Tikhon et sera rejointe par d’autres évêques déjà en poste à l’étranger. </p>
                    <p>Le 8 avril 1921, les édits Nos. 423 et 424 du patriarche Tikhon confirment la décision prise encore en Crimée par la Haute Administration ecclésiastique provisoire du sud-est de la Russie de nommer Monseigneur Euloge à la tête des paroisses et fidèles russes en Europe occidentale et institue une Administration provisoire des paroisses russes en Europe occidentale. Ce vaste diocèse, inclut également à l’époque, plusieurs territoires de l’Europe centrale.</p>
                    <p>Après une brève installation en Allemagne, Monseigneur Euloge transfère le siège de son diocèse à Paris, où la grande église du 12 Rue Daru, qui fut autrefois, près de l’Arc de Triomphe, celle de l’ambassade russe, devient la cathédrale. </p>
                    <p>	L’Archevêché sera imprégné des deux caractéristiques induites par le métropolite Euloge : héritage de la tradition spirituelle orthodoxe russe, telle qu’elle fut régénérée par le Concile de Moscou de 1917-1918 (préoccupation pastorale, accueil des migrants) et mission sur la terre d’accueil, celle-ci s’inscrivant nécessairement dans une perspective de renouvellement et de diversification.</p>
                    <p>Au-delà des péripéties de l'histoire et des secousses ecclésiologiques-canoniques qui l’ont agité, il apparaît clairement que l'Archevêché a constitué un espace ecclésial privilégié de témoignages et de mission. </p>
                    <p>Même s’il ne faut pas oublier quelques grands noms restés fidèles au patriarcat de Moscou ou à l’ « Eglise Russe Hors-Frontières » (dont l’Archevêché sera malheureusement administrativement séparé), l'essentiel du rayonnement de l'orthodoxie dans la diaspora en Europe de l’ouest, dans la première moitié du 20e siècle est dû aux théologiens regroupés autour de l'Institut Saint-Serge à Paris – qui compte Monseigneur Euloge parmi ses fondateurs – dont sont issus tous les théologiens formés dans cette tradition orthodoxe parisienne et notamment ceux qui ont élevé le Séminaire Saint Vladimir à New York au niveau d’une université à la réputation mondiale. </p>
                    <p>Cette école, qualifiée d’«Ecole de Paris », a réaffirmé en les redécouvrant dans le prolongement de la renaissance théologique et spirituelle russe, la théologie, la spiritualité et l’ecclésiologie orthodoxes. Ce faisant, elle a suscité une ouverture et un accueil bienveillant, qui explique aujourd'hui la dimension européenne de l'Archevêché, sa pluriethnicité et son plurilinguisme liturgique. C'est par ce témoignage ouvert et unifiant, porté par le testament spirituel du Métropolite Euloge - « La liberté d’esprit dans l’Église est sacrée » que de nombreux membres de l'Archevêché, clercs et laïcs, ont largement contribué, avec d'autres, à la rencontre avec les orthodoxes d'autres origines nationales et juridictionnelles.</p>
                    
                    <h3>Comment les liens avec d’autres églises russes se sont-ils distendus pendant si longtemps ?</h3>
                    <p>En novembre 1921, la Haute Administration se rassemble en Concile à Sremski-Karlovcy (royaume des Serbes, Croates et Slovènes, future Yougoslavie). Mais le Concile ne pourra jouer le rôle fédérateur qu’on en attendait.</p>
                    <p>Monseigneur Euloge et un petit nombre d’évêques s’opposèrent  à une majorité qui se forma pour voter des résolutions politiques extrêmes : l’exigence d’une restauration de la monarchie et en particulier de la dynastie des Romanov, plus un appel à mener une guerre internationale contre le pouvoir soviétique. En soutenant  un projet de restauration des Romanov, l’Eglise se serait retrouvée au milieu d’une crise dynastique divisant les survivants de la famille impériale décimée par les massacres.  D’autre part, une prise de position résolument monarchiste excluait les nombreux fidèles qui n’adhéraient pas à cette idéologie, dont de nombreux membres non seulement du clergé mais aussi des membres des cadres de l’armée et des gouvernements « blancs ». L’Eglise risquait ainsi de perdre son rôle fédérateur parmi les centaines de milliers d’exilés. Plus grave encore, un appel direct aux armes par l’Eglise en exil , aurait nécessairement eu  des conséquences mortelles sans aucun doute envisagées par Monseigneur Euloge et ceux qui furent mis en minorité. Si une grande guerre contre un gouvernement terroriste et génocidaire peut se comprendre encore aujourd’hui comme nécessaire, le seul résultat qu’on pouvait attendre, en 1921, d’un appel officiel aux armes par des évêques en exil, alors que les grandes puissances n’aidèrent les armées blanches en débâcle que du bout des lèvres et allaient très prochainement, les unes après les autres, reconnaître l’Etat soviétique, auraient l’extrême aggravation de la condition des ecclésiastiques et des fidèles restés dans leurs paroisses, déjà en proie à de terribles répressions, et ce à commencer par le patriarche Tikhon, véritable otage des forces soviétiques.  D’ailleurs, les résolutions du Concile de Sremski-Karlovcy servirent immédiatement de prétexte au pouvoir soviétique pour renforcer leurs répressions contre l’Eglise. </p>
                    <p>Le 5 mai 1922, un édit signé par Tikhon avec l’approbation de toute l’administration ecclésiale restée en Russie, retira son homologation à la Haute Administration tout en confirmant l’autorité sur l’Europe de l’Ouest du métropolite Euloge. Les évêques, prêtres et laïques formant la majorité du Concile à Sremski-Karlovcy et considérant que le patriarche Tikhon n’était plus libre de ses paroles se réorganisèrent en « Eglise Russe Hors-Frontière ». Bien que la situation restât extrêmement tendue avec le Métropolite Euloge, ce dernier fit un effort pour ne pas rompre officiellement les liens avec l’Eglise Russe Hors-Frontières. Il ne chercha pas à imposer son autorité en Europe occidentale sur les ecclésiastiques reconnaissant l’autorité de l’Eglise Hors-Frontières. En même temps, marchant sur une corde raide, il essayait de garder le contact avec l'église-mère de Moscou et son primat, le patriarche Tikhon puis son successeur le métropolite Serge, tout en comprenant que ce dernier n'était plus qu’un prisonnier du régime privé de presque toute initiative et parole libre. En 1927 il fut définitivement condamné par l'église Hors Frontières qui considérait que ce maintien du lien avec Moscou était allé beaucoup trop loin. En 1930 c’est le métropolite Serge, à l'évidence forcé par le pouvoir soviétique, qui « déposa » le métropolite Euloge pour avoir participé à un vaste mouvement de prière international en faveur des chrétiens persécutés – ce qui fut relayé par la presse soviétique comme un acte anti-soviétique diffamatoire et hostile.</p>
                    <p>Dans ces conditions et afin d’échapper à une situation canonique inédite , l’Archevêché de Monseigneur Euloge chercha la protection du « premier parmi les égaux » des primats de l’Eglise Orthodoxe – le patriarche de Constantinople. Ainsi, le 17 février 1931, le patriarche œcuménique Photius II accepta le diocèse de Monseigneur Euloge au sein de son patriarcat avec le statut d’exarchat provisoire. Dans le même temps, le métropolite Euloge affirmait : " bien sûr, nous ne nous faisons pas sécession, nous ne nous séparons pas de l'Église-Mère russe". L’Archevêché se maintiendra au sein du patriarcat de Constantinople sous différentes appellations et sous différents statuts jusqu’en 2019 où la majorité des membres de son clergé et de ses conseils paroissiaux vota de rejoindre le patriarcat de Moscou.</p>
                    <p>Malgré les divisions, l’Archevêché maintint des liens, notamment de prière ou d’amitié personnelle avec des membres  du patriarcat de Moscou et l’Eglise Russe Hors-Frontière. Les métropolites Euloge et Antonij (Khrapovitsky), primat de l’Eglise Hors-Frontière, connurent un moment de réconciliation au cours de rencontres tentant de reformer des liens officiels. Les Eglises de Serbie (où de grands efforts furent entrepris pour une réunification définitive) et de Jérusalem jouèrent le rôle de conciliatrices et un lien spirituel se maintint entre les trois juridictions séparées à travers ces deux patriarcats. Malgré les divisions, plusieurs concélébrations eurent lieu entre des évêques de l’Archevêché et l’Eglise Hors-Frontière, et des évêques de l’Archevêché et du patriarcat de Moscou. Des paroissiens éminents du patriarcat de Moscou et de l’Eglise Hors-Frontières,  ont contribué également au rayonnement de l’Archevêché par leur travail au sein de ses institutions. Les associations de jeunesse ont servi de lieu de convivialité entre paroissiens des différentes juridictions (l’ACER rassemblant des jeunes de l’Archevêché et du patriarcat de Moscou, les Vitiaz rassemblant ceux de l’Archevêché et de l’Eglise Hors-Frontières, ainsi que du patriarcat de Moscou dès la fin des années 1980) et ont également servi de terrain de rencontre entre les prélats.</p>
                    <p>S’il y eut des bons rapports entre l’Archevêché et les autres juridictions russes, ils ont été certes plutôt officieux qu’officiels, mais ont été respectueux, voire cordiaux. Des contacts personnels réguliers se sont maintenus pendant des années entre prêtres et surtout entre laïcs autour de projets communs importants (humanitaires, culturels, éducatifs). Surtout, de nombreux liens familiaux ou amicaux gommaient nombre de différences. D’innombrables festivités, travaux éducatifs et autres rencontres d’ordre culturel, s’organisèrent lors de moments sinon de réconciliation informelle, du moins dans des moments de dialogue.</p>
                    <p>Les trois juridictions devraient être considérées comme définitivement réconciliées depuis le rattachement de l’Eglise Hors-Frontières au patriarcat de Moscou en 2009 et de l’Archevêché en 2019. </p>

                    <h3>L’Archevêché du 21ème siècle : dans un nouveau monde .</h3>
                    <p>Mondialisation, échanges accélérés entre l’Europe de l’Ouest et les pays slaves de l’Est et  mutation des sociétés de l’Europe Occidentale par la diversification ethnique et religieuse due à l’immigration d’Afrique et d’Asie – voici une situation rapidement changeante et qui place l’Archevêché dans un environnement bien différent de celui des années 1930 (un environment dans lequel les églises étaient formées par des paroissiens ayant tout perdu, obligés de s’adapter à une société étrangère) et bien différent  de celui des années 1960 et 1970, époque à laquelle on débattait d’un effacement imminent de la culture russe des descendants des immigrés et de leur capacité à s’adapter ou non à une société encore très catholique ou protestante et où les immigrés du Maghreb, d’Afrique sub-tropicale ou de pays encore plus lointains n’avaient pas encore bouleversé la réalité sociale de l’Europe de l’Ouest.</p>
                    <p> Au XXIe siècle, avec une arrivée massive de russophones et d’autres Slaves immigrés – installés définitivement, expatriés provisoires, ou voyageurs de passage – mais aussi, avec l’apparition de nouveaux paroissiens originaires des cultures du monde entier convertis à l’orthodoxie (y compris des prêtres et des diacres) et convergeant vers les grandes métropoles de l’Europe de l’Ouest, l’Archevêché, cent ans après sa formation, est face à de nouveaux défis et de nouvelles vocations.</p>
                    <p>L’Archevêché, diocèse rattaché aujourd’hui au Patriarcat de Moscou, bénéficiant de l'autonomie essentielle – théologique, liturgique et pastorale, mais aussi administrative et financière – dispose de tous les atouts pour poursuivre la mission qui fut la sienne en définitive depuis ses origines : témoigner de la foi orthodoxe ici et maintenant et œuvrer à son unité dans ce monde « afin que le monde croie ». Sur cette base et dans cette perspective, l'Archevêché, en dépit des difficultés et obstacles d’ordre géopolitique, participera à toute initiative susceptible d’améliorer la situation canonique de l’orthodoxie locale dans le respect de l’ecclésiologie de communion. </p>
                    <p>En outre, vivant dans des contrées où l'Orthodoxie est minoritaire, l’Archevêché entend poursuivre son témoignage également dans le respect des identités chrétiennes locales héritières d’autres traditions spirituelles et théologiques. Ainsi les communautés de l'Archevêché établissent, entretiennent et développent des relations fraternelles avec les communautés chrétiennes d'autres confessions, dont elles reçoivent parfois aide et soutien. Elles participent souvent, à l'instar du métropolite Euloge, au dialogue œcuménique et aux prières pour l'unité des chrétiens, et créent des liens au niveau des communautés paroissiales tout en donnant un témoignage de service commun dans la société.</p>


               </div>
            </main>
        </div>
    );
}

export async function getStaticProps(context) {

    const menu = await getMenu(context.locale)
  
    return {props: {
      menu: menu
    }}
  }
    